CREATE TABLE IF NOT EXISTS vehicle (
  id INT AUTO_INCREMENT PRIMARY KEY,
  brand VARCHAR(255) NOT NULL, 
  model VARCHAR(255) NOT NULL, 
  year INT NOT NULL, 
  license_plate VARCHAR(10) UNIQUE NOT NULL, 
  color VARCHAR(100),
  mileage INT NOT NULL DEFAULT 0, 
  available BOOLEAN NOT NULL DEFAULT TRUE,
  daily_charge DECIMAL(10,2),
  registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  ) ENGINE=InnoDB DEFAULT CHARSET=latin1

CREATE TABLE IF NOT EXISTS user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  cpf VARCHAR(11),
  email VARCHAR(100) UNIQUE NOT NULL,
  birth_at DATE NOT NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=latin1

CREATE TABLE IF NOT EXISTS employee (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  cpf VARCHAR(11),
  email VARCHAR(100) UNIQUE NOT NULL,
  role VARCHAR(100)
  ) ENGINE=InnoDB DEFAULT CHARSET=latin1

CREATE TABLE IF NOT EXISTS rental (
  id INT AUTO_INCREMENT PRIMARY KEY,
  rent_date DATE NOT NULL DEFAULT CURRENT_DATE,
  return_date DATE NOT NULL, 
  rent_value INT NOT NULL, 
  id_user INT,
  id_vehicle INT,
  id_employee INT, 
  
  FOREIGN KEY (id_user) REFERENCES user(id),
  FOREIGN KEY (id_vehicle) REFERENCES vehicle(id),
  FOREIGN KEY (id_employee) REFERENCES employee(id)
  ) ENGINE=InnoDB DEFAULT CHARSET=latin1





